1c1
< FROM openjdk:8-jdk
---
> FROM napnap75/rpi-openjdk-official:8-jdk
29c29
< ENV TINI_SHA 6c41ec7d33e857d4779f14d9c74924cab0c7973485d2972419a3b7c7620ff5fd
---
> ENV TINI_SHA a3a93909aedf67d6b51c1dc40f63d3caf5ec1f5bc2619fc1daaa9ff81ab1ef26
32c32
< RUN curl -fsSL https://github.com/krallin/tini/releases/download/v${TINI_VERSION}/tini-static-amd64 -o /bin/tini && chmod +x /bin/tini \
---
> RUN curl -fsSL https://github.com/krallin/tini/releases/download/v${TINI_VERSION}/tini-static-armhf -o /bin/tini && chmod +x /bin/tini \
