language: bash
services: docker
sudo: required

notifications:
  email: false
  slack:
    rooms:
      - secure: KYnSm6QnVZit06xZA8++6z3xeX8pYeoNIFkDh0aU0LaZGDJ5+CtgnmAzoBMi3Kn523s1jSbGIXY95VTTdr88pVJXzYIFKRPQku8U7Iq80wden/frtjZBUt97bPghlEO73MOIl/hWOAWi0jRKS/h0aGf3iWbyEm8x4VVbta2JRnTSGClXw0Db8UZ+i6VdTMGc59tNPOsEe0wDDY+p1NFEEnLf2lz51tW2SIeoxSK9jq2kDKQwUmHRxyl6ConyJFbCTOhqVw8boq5X5HSPHQpBmtAJNqYJZtR/9rfORJs7ARVBlIWM0qKHwWuLzxhZof4TiFoCshln94OdMtK4Vvu99B0PF7W/mAsBzAYT2d4un1my5Z8fkMgx2eg4g4D1N4fKqViqx/iJnV6J3U6u0SBP3/c0CITpT1lsO9bhgbr1Tr0us3ARE94MPBude2j2yWh9EnnhPQowLC9utv89uvQFyHSy8esBStFElHH6lKKhzTOwsB5ewL4Lk0ziZlUb9amXJDWrB2FHTTYiyoXE4lMLA3HzEYrQKms9heGyqeaUhOWfeLg1iKUzCMKWvOgof7cfY9lsFk1nZqsJJyPDOwq9hmrsH3QGAUyBmn5y57DyfPnDtMaHAkJaqIuLegYGUaNad4x2sxw73hjyXA9Y4USvWj8GPM4u8fyMxZg+KtCJkLw=
    on_success: change
    
env:
  - IMAGE=influxdb LABEL=1.3
  
install:
  - docker run --rm --privileged multiarch/qemu-user-static:register
  
script:
# Build
  - cd ${IMAGE}
  - ./build.sh ${LABEL}
    
after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" ;
      docker push napnap75/rpi-${IMAGE}:${LABEL} ;
    fi
    
