language: bash
services: docker
sudo: required

notifications:
  email: false
  slack:
    rooms:
      - secure: 1ng6+iy6axQ/wJQ7q/cDK5wnF+8AWHhfMLCHHjFmL9e+F8RU1sjz9KmZm7z1NWHNGTf8rCP33tB8BH7T+HlZUKBbZHgaLemQz3R/GFARDu33lxaDpUrMLySAwCre5M2/sb73iQ25zACPeV0qA/93n6Qv5gASoaQMjpSS3kOSIsQWkbwMcInMaMXBarSKR9pdcoQxhv/pzCXVvTKBfF7RGQy0AcFUfjFvfG9LV4ReHw6o2ZjtA3gB7mjVDjy8WpoVsJFj0Ju/gu3IKJgwpuYBiQm7SKLBG2qMutIRZUJw73Qqhuqdk9Z/RFpQk11GVcxcyhATV+Q+tZPpJb+asD4fVfSK3fgl6VNoyPztu9n070zhmB0M6VIBS+4xjq36VS07onRpyY2YqqU/EWoJsaYdCqtI8qH3sXDfH6pXDXUq8o042u+A2nHmkS3y/xjQIIVPCE9vfNcy3LmVvOMud0T2nRVtSBwde1zmJqdxhNkCQxLhckUisCANy5fDMaYteb/vof4helTh6ifUchaDq67uIokZf07gTcf+ApGQaq5Y3j+rw5QRvrQN25vYmZmk9FJz0/TGZa0JHpFWK8xeobA7bRdg+RKRvSNZphP4vqgCb2Ee9V7RlKWNHIA1NQsx/917YCwoCMw61G0pSYdsw7jz63+/yd3etfQM0beUEZCrcVo=
    on_success: change
    
env:
  - IMAGE=influxdb VERSION=1.7 VARIANT=alpine LATEST=true
  - IMAGE=telegraf VERSION=1.11 VARIANT=alpine LATEST=true
  - IMAGE=chronograf VERSION=1.7 VARIANT=alpine LATEST=true
  - IMAGE=kapacitor VERSION=1.5 VARIANT=alpine LATEST=true
  - IMAGE=jeedom VERSION=latest
  - IMAGE=jeedom VERSION=openzwave
  - IMAGE=jeedom VERSION=mqtt
  - IMAGE=jeedom VERSION=ozw-mqtt
  
install:
  - docker run --rm --privileged multiarch/qemu-user-static:register
  
script:
# Build
  - cd ${IMAGE}
  - ./build.sh ${VERSION} ${VARIANT}
    
after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" ;
      IMAGE_NAME= ;
      if [ "$VARIANT" == "" ]; then IMAGE_NAME="rpi-${IMAGE}:${VERSION}" ; else IMAGE_NAME="rpi-${IMAGE}:${VERSION}-${VARIANT}" ; fi ;
      docker push napnap75/${IMAGE_NAME} ;
      if [ "$LATEST" == "true" ]; then
        docker tag napnap75/${IMAGE_NAME} napnap75/rpi-${IMAGE}:latest ;
        docker push napnap75/rpi-${IMAGE}:latest ;
      fi ;
      VERSION_FULL=$(docker run --rm napnap75/${IMAGE_NAME} env | grep $(tr '[a-z]' '[A-Z]' <<< ${IMAGE})_VERSION | egrep -o "[0-9\.]+") ;
      if [ "$VERSION_FULL" != "" ]; then
        if [ "$VARIANT" == "" ]; then 
          docker tag napnap75/${IMAGE_NAME} napnap75/rpi-${IMAGE}:${VERSION_FULL} ;
          docker push napnap75/rpi-${IMAGE}:${VERSION_FULL} ;
        else
          docker tag napnap75/${IMAGE_NAME} napnap75/rpi-${IMAGE}:${VERSION_FULL}-${VARIANT} ;
          docker push napnap75/rpi-${IMAGE}:${VERSION_FULL}-${VARIANT} ;
        fi ;
      fi ;
    fi
