--- Dockerfile.amd64
+++ Dockerfile.armhf
@@ -1,4 +1,5 @@
-FROM alpine:3.5
+FROM arm32v6/alpine:3.5
+ADD qemu-arm-static /usr/bin
 
 RUN echo 'hosts: files dns' >> /etc/nsswitch.conf
 RUN apk add --no-cache ca-certificates && \
@@ -15,14 +16,13 @@
         gpg --keyserver pgp.mit.edu --recv-keys "$key" || \
         gpg --keyserver keyserver.pgp.com --recv-keys "$key" ; \
     done && \
-    wget -q https://dl.influxdata.com/kapacitor/releases/kapacitor-${KAPACITOR_VERSION}-static_linux_amd64.tar.gz.asc && \
-    wget -q https://dl.influxdata.com/kapacitor/releases/kapacitor-${KAPACITOR_VERSION}-static_linux_amd64.tar.gz && \
-    gpg --batch --verify kapacitor-${KAPACITOR_VERSION}-static_linux_amd64.tar.gz.asc kapacitor-${KAPACITOR_VERSION}-static_linux_amd64.tar.gz && \
+    wget -q https://dl.influxdata.com/kapacitor/releases/kapacitor-${KAPACITOR_VERSION}_linux_armhf.tar.gz.asc && \
+    wget -q https://dl.influxdata.com/kapacitor/releases/kapacitor-${KAPACITOR_VERSION}_linux_armhf.tar.gz && \
+    gpg --batch --verify kapacitor-${KAPACITOR_VERSION}_linux_armhf.tar.gz.asc kapacitor-${KAPACITOR_VERSION}_linux_armhf.tar.gz && \
     mkdir -p /usr/src && \
-    tar -C /usr/src -xzf kapacitor-${KAPACITOR_VERSION}-static_linux_amd64.tar.gz && \
-    rm -f /usr/src/kapacitor-*/kapacitor.conf && \
-    chmod +x /usr/src/kapacitor-*/* && \
-    cp -a /usr/src/kapacitor-*/* /usr/bin/ && \
+    tar -C /usr/src -xzf kapacitor-${KAPACITOR_VERSION}_linux_armhf.tar.gz && \
+    chmod +x /usr/src/kapacitor-*/usr/bin/* && \
+    cp -a /usr/src/kapacitor-*/usr/bin/* /usr/bin/ && \
     rm -rf *.tar.gz* /usr/src /root/.gnupg && \
     apk del .build-deps
 COPY kapacitor.conf /etc/kapacitor/kapacitor.conf
