--- Dockerfile.amd64
+++ Dockerfile.armhf
@@ -1,4 +1,5 @@
-FROM alpine:3.8
+FROM arm32v6/alpine:3.8
+ADD qemu-arm-static /usr/bin
 
 RUN echo 'hosts: files dns' >> /etc/nsswitch.conf
 RUN apk add --no-cache ca-certificates && \
@@ -15,14 +16,13 @@
         gpg --keyserver pgp.mit.edu --recv-keys "$key" || \
         gpg --keyserver keyserver.pgp.com --recv-keys "$key" ; \
     done && \
-    wget --no-verbose https://dl.influxdata.com/chronograf/releases/chronograf-${CHRONOGRAF_VERSION}-static_linux_amd64.tar.gz.asc && \
-    wget --no-verbose https://dl.influxdata.com/chronograf/releases/chronograf-${CHRONOGRAF_VERSION}-static_linux_amd64.tar.gz && \
-    gpg --batch --verify chronograf-${CHRONOGRAF_VERSION}-static_linux_amd64.tar.gz.asc chronograf-${CHRONOGRAF_VERSION}-static_linux_amd64.tar.gz && \
+    wget --no-verbose https://dl.influxdata.com/chronograf/releases/chronograf-${CHRONOGRAF_VERSION}_linux_armhf.tar.gz.asc && \
+    wget --no-verbose https://dl.influxdata.com/chronograf/releases/chronograf-${CHRONOGRAF_VERSION}_linux_armhf.tar.gz && \
+    gpg --batch --verify chronograf-${CHRONOGRAF_VERSION}_linux_armhf.tar.gz.asc chronograf-${CHRONOGRAF_VERSION}_linux_armhf.tar.gz && \
     mkdir -p /usr/src && \
-    tar -C /usr/src -xzf chronograf-${CHRONOGRAF_VERSION}-static_linux_amd64.tar.gz && \
-    rm -f /usr/src/chronograf-*/chronograf.conf && \
-    chmod +x /usr/src/chronograf-*/* && \
-    cp -a /usr/src/chronograf-*/* /usr/bin/ && \
+    tar -C /usr/src -xzf chronograf-${CHRONOGRAF_VERSION}_linux_armhf.tar.gz && \
+    chmod +x /usr/src/chronograf-*/usr/bin/* && \
+    cp -a /usr/src/chronograf-*/usr/bin/* /usr/bin/ && \
     rm -rf *.tar.gz* /usr/src /root/.gnupg && \
     apk del .build-deps
 
