--- Dockerfile.amd64
+++ Dockerfile.armhf
@@ -1,4 +1,5 @@
-FROM alpine:3.5
+FROM arm32v6/alpine:3.5
+ADD qemu-arm-static /usr/bin
 
 RUN echo 'hosts: files dns' >> /etc/nsswitch.conf
 RUN apk add --no-cache tzdata bash
@@ -14,11 +15,11 @@
         gpg --keyserver pgp.mit.edu --recv-keys "$key" || \
         gpg --keyserver keyserver.pgp.com --recv-keys "$key" ; \
     done && \
-    wget -q https://dl.influxdata.com/influxdb/releases/influxdb-${INFLUXDB_VERSION}-static_linux_amd64.tar.gz.asc && \
-    wget -q https://dl.influxdata.com/influxdb/releases/influxdb-${INFLUXDB_VERSION}-static_linux_amd64.tar.gz && \
-    gpg --batch --verify influxdb-${INFLUXDB_VERSION}-static_linux_amd64.tar.gz.asc influxdb-${INFLUXDB_VERSION}-static_linux_amd64.tar.gz && \
+#    wget -q https://dl.influxdata.com/influxdb/releases/influxdb-${INFLUXDB_VERSION}_linux_armhf.tar.gz.asc && \
+    wget -q https://dl.influxdata.com/influxdb/releases/influxdb-${INFLUXDB_VERSION}_linux_armhf.tar.gz && \
+#    gpg --batch --verify influxdb-${INFLUXDB_VERSION}_linux_armhf.tar.gz.asc influxdb-${INFLUXDB_VERSION}_linux_armhf.tar.gz && \
     mkdir -p /usr/src && \
-    tar -xzf influxdb-${INFLUXDB_VERSION}-static_linux_amd64.tar.gz && \
+    tar -xzf influxdb-${INFLUXDB_VERSION}_linux_armhf.tar.gz && \
     chmod +x /usr/bin/influx_inspect /usr/bin/influx_stress /usr/bin/influxd /usr/bin/influx_tsm /usr/bin/influx && \
     rm -rf *.tar.gz* /usr/src /root/.gnupg /etc/influxdb/influxdb.conf && \
     apk del .build-deps
